#!/usr/bin/env bash
# providers/hermes/run.sh
# Executes the Hermes provider session.
# Called by scripts/start_agent.sh after pre-flight and compose generation.
#
# Usage:
#   ./run.sh <mode> --name=<project_name> --sandbox=<path> --compose-file=<path>
#
# Modes:
#   standard   — Hermes chat TUI attached to terminal
#   serve      — Hermes in API mode, Open WebUI exposed at SERVE_PORT
#   dry-run    — liveness check only
#   headless   — reserved, not yet implemented
#
# The compose file is fully merged and generated by start_agent.sh.
# This script does not resolve or assemble compose files.

set -euo pipefail

# -------------------------
# Paths
# -------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# REPO_ROOT assumes this script lives at providers/hermes/
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

source "$REPO_ROOT/libs/containers.sh"
source "$REPO_ROOT/libs/compose.sh"

# -------------------------
# Args
# -------------------------
MODE="${1:-}"
shift || true

if [[ -z "$MODE" ]]; then
  echo "Usage: $0 <mode:standard|dry-run|serve> --name=<n> --sandbox=<path> --compose-file=<path>"
  exit 1
fi

# -------------------------
# Flag parsing
# -------------------------
PROJECT_NAME=""
SANDBOX_DIR=""
PROVIDER_NAME="hermes"
COMPOSE_FILE=""

for ARG in "$@"; do
  case "$ARG" in
    --name=*)         PROJECT_NAME="${ARG#--name=}" ;;
    --sandbox=*)      SANDBOX_DIR="${ARG#--sandbox=}" ;;
    --compose-file=*) COMPOSE_FILE="${ARG#--compose-file=}" ;;
    *)
      echo "Unknown flag: $ARG"
      exit 1
      ;;
  esac
done

if [[ -z "$PROJECT_NAME" || -z "$SANDBOX_DIR" || -z "$COMPOSE_FILE" ]]; then
  echo "Error: --name, --sandbox, and --compose-file are required"
  exit 1
fi

# Clean up the generated tmpfile on exit — start_agent.sh passes ownership here.
trap 'rm -f "$COMPOSE_FILE"' EXIT

# -------------------------
# SERVE_PORT resolution
# -------------------------
SERVE_PORT_DEFAULT=46553
if [[ -z "${SERVE_PORT:-}" ]]; then
  echo "Warning: SERVE_PORT is not set in .env — falling back to default ($SERVE_PORT_DEFAULT)"
  SERVE_PORT="$SERVE_PORT_DEFAULT"
fi

# -------------------------
# Compose args
# -------------------------
compose_args "$PROJECT_NAME" "$SANDBOX_DIR" "$COMPOSE_FILE"

# -------------------------
# Mode dispatch
# -------------------------
case "$MODE" in
  dry-run)
    echo "Running dry-run..."
    DRY_RUN_SCRIPT="$(realpath "$REPO_ROOT/scripts/dry_run.sh")"
    compose_dry_run "$DRY_RUN_SCRIPT"
    exit 0
    ;;

  serve|standard)
    # Handled below
    ;;

  headless)
    echo "Error: headless mode is reserved and not yet implemented"
    exit 1
    ;;

  *)
    echo "Error: unsupported mode '$MODE'. Supported modes: standard, dry-run, serve"
    exit 1
    ;;
esac

# -------------------------
# Run
# -------------------------
compose_teardown

if [[ "$MODE" == "serve" ]]; then
  echo "Starting agent: $PROJECT_NAME (serve mode — Hermes API + Open WebUI)"
  docker compose "${COMPOSE_ARGS[@]}" up -d
  echo "Open WebUI available at http://127.0.0.1:${SERVE_PORT}"
  echo "Hermes API available at http://127.0.0.1:8642/v1"
  echo "Stop with: make stop"
else
  echo "Starting agent: $PROJECT_NAME"
  echo "+ starting sandbox..."
  docker compose "${COMPOSE_ARGS[@]}" up -d sandbox

  compose_sandbox_wait "$PROJECT_NAME"

  echo "+ attaching to agent (TUI)..."
  docker compose "${COMPOSE_ARGS[@]}" run --rm agent chat

  echo "+ tearing down..."
  docker compose "${COMPOSE_ARGS[@]}" down -v
fi
